services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    env_file:
      - .env
    image: venkatbalajimadheswaran/auth-service:latest

  employee-service:
    build:
      context: ./employee-service
      dockerfile: Dockerfile
    env_file:
      - .env
    image: venkatbalajimadheswaran/employee-service:latest

  department-service:
    build:
      context: ./department-service
      dockerfile: Dockerfile
    env_file:
      - .env
    image: venkatbalajimadheswaran/department-service:latest
