// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: protos/auth_service.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_protos_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_protos_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyTokenRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	EmployeeId    int64                  `protobuf:"varint,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_protos_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_protos_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyTokenResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VerifyTokenResponse) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

var File_protos_auth_service_proto protoreflect.FileDescriptor

const file_protos_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x19protos/auth_service.proto\x12\fauth_service\"(\n" +
	"\x12VerifyTokenRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"R\n" +
	"\x13VerifyTokenResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1f\n" +
	"\vemployee_id\x18\x02 \x01(\x03R\n" +
	"employeeId2a\n" +
	"\vAuthService\x12R\n" +
	"\vVerifyToken\x12 .auth_service.VerifyTokenRequest\x1a!.auth_service.VerifyTokenResponseB\x04Z\x02./b\x06proto3"

var (
	file_protos_auth_service_proto_rawDescOnce sync.Once
	file_protos_auth_service_proto_rawDescData []byte
)

func file_protos_auth_service_proto_rawDescGZIP() []byte {
	file_protos_auth_service_proto_rawDescOnce.Do(func() {
		file_protos_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_auth_service_proto_rawDesc), len(file_protos_auth_service_proto_rawDesc)))
	})
	return file_protos_auth_service_proto_rawDescData
}

var file_protos_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_auth_service_proto_goTypes = []any{
	(*VerifyTokenRequest)(nil),  // 0: auth_service.VerifyTokenRequest
	(*VerifyTokenResponse)(nil), // 1: auth_service.VerifyTokenResponse
}
var file_protos_auth_service_proto_depIdxs = []int32{
	0, // 0: auth_service.AuthService.VerifyToken:input_type -> auth_service.VerifyTokenRequest
	1, // 1: auth_service.AuthService.VerifyToken:output_type -> auth_service.VerifyTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_auth_service_proto_init() }
func file_protos_auth_service_proto_init() {
	if File_protos_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_auth_service_proto_rawDesc), len(file_protos_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_auth_service_proto_goTypes,
		DependencyIndexes: file_protos_auth_service_proto_depIdxs,
		MessageInfos:      file_protos_auth_service_proto_msgTypes,
	}.Build()
	File_protos_auth_service_proto = out.File
	file_protos_auth_service_proto_goTypes = nil
	file_protos_auth_service_proto_depIdxs = nil
}
